"""sync_multimodal_pipeline_v3

Revision ID: a2266ef816ba
Revises: 
Create Date: 2026-08-20 17:27:36.296330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'a2266ef816ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_constraint(op.f('event_facts_raw_id_fkey'), 'event_facts', schema='core', type_='foreignkey')
    op.create_foreign_key(None, 'event_facts', 'event_raw', ['raw_id'], ['raw_id'], source_schema='core', referent_schema='raw')
    op.drop_constraint(op.f('fact_activity_template_event_id_fkey'), 'fact_activity_template', schema='domain', type_='foreignkey')
    op.create_foreign_key(None, 'fact_activity_template', 'event_facts', ['event_id'], ['event_id'], source_schema='domain', referent_schema='core')
    op.drop_constraint(op.f('fact_header_template_event_id_fkey'), 'fact_header_template', schema='domain', type_='foreignkey')
    op.create_foreign_key(None, 'fact_header_template', 'event_facts', ['event_id'], ['event_id'], source_schema='domain', referent_schema='core')
    op.drop_constraint(op.f('fact_item_template_event_id_fkey'), 'fact_item_template', schema='domain', type_='foreignkey')
    op.create_foreign_key(None, 'fact_item_template', 'fact_header_template', ['event_id'], ['event_id'], source_schema='domain', referent_schema='domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_item_template', schema='domain', type_='foreignkey')
    op.create_foreign_key(op.f('fact_item_template_event_id_fkey'), 'fact_item_template', 'fact_header_template', ['event_id'], ['event_id'], source_schema='domain', referent_schema='domain', ondelete='CASCADE')
    op.drop_constraint(None, 'fact_header_template', schema='domain', type_='foreignkey')
    op.create_foreign_key(op.f('fact_header_template_event_id_fkey'), 'fact_header_template', 'event_facts', ['event_id'], ['event_id'], source_schema='domain', referent_schema='core', ondelete='CASCADE')
    op.drop_constraint(None, 'fact_activity_template', schema='domain', type_='foreignkey')
    op.create_foreign_key(op.f('fact_activity_template_event_id_fkey'), 'fact_activity_template', 'event_facts', ['event_id'], ['event_id'], source_schema='domain', referent_schema='core', ondelete='CASCADE')
    op.drop_constraint(None, 'event_facts', schema='core', type_='foreignkey')
    op.create_foreign_key(op.f('event_facts_raw_id_fkey'), 'event_facts', 'event_raw', ['raw_id'], ['raw_id'], source_schema='core', referent_schema='raw', ondelete='SET NULL')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
