"""add_event_date_to_event_memories

Revision ID: f1ed3329d581
Revises: a2266ef816ba
Create Date: 2026-08-21 17:44:55.085095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1ed3329d581'
down_revision: Union[str, Sequence[str], None] = 'a2266ef816ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_memories',
    sa.Column('memory_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('base_entity_id', sa.BigInteger(), nullable=False),
    sa.Column('target_entity_id', sa.BigInteger(), nullable=False),
    sa.Column('target_object_id', sa.BigInteger(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('domain_context', sa.String(length=50), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('source_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exp_ts', sa.DateTime(), nullable=True),
    sa.Column('ne_ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_entity_id'], ['domain.mst_entities.entity_id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['domain.mst_entities.entity_id'], ),
    sa.ForeignKeyConstraint(['target_object_id'], ['domain.mst_objects.object_id'], ),
    sa.PrimaryKeyConstraint('memory_id'),
    schema='core'
    )
    op.drop_table('alembic_version')
    op.drop_constraint(op.f('event_facts_raw_id_fkey'), 'event_facts', schema='core', type_='foreignkey')
    op.create_foreign_key(None, 'event_facts', 'event_raw', ['raw_id'], ['raw_id'], source_schema='core', referent_schema='raw')
    op.drop_constraint(op.f('fact_activity_template_event_id_fkey'), 'fact_activity_template', schema='domain', type_='foreignkey')
    op.create_foreign_key(None, 'fact_activity_template', 'event_facts', ['event_id'], ['event_id'], source_schema='domain', referent_schema='core')
    op.drop_constraint(op.f('fact_header_template_event_id_fkey'), 'fact_header_template', schema='domain', type_='foreignkey')
    op.create_foreign_key(None, 'fact_header_template', 'event_facts', ['event_id'], ['event_id'], source_schema='domain', referent_schema='core')
    op.drop_constraint(op.f('fact_item_template_event_id_fkey'), 'fact_item_template', schema='domain', type_='foreignkey')
    op.create_foreign_key(None, 'fact_item_template', 'fact_header_template', ['event_id'], ['event_id'], source_schema='domain', referent_schema='domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_item_template', schema='domain', type_='foreignkey')
    op.create_foreign_key(op.f('fact_item_template_event_id_fkey'), 'fact_item_template', 'fact_header_template', ['event_id'], ['event_id'], source_schema='domain', referent_schema='domain', ondelete='CASCADE')
    op.drop_constraint(None, 'fact_header_template', schema='domain', type_='foreignkey')
    op.create_foreign_key(op.f('fact_header_template_event_id_fkey'), 'fact_header_template', 'event_facts', ['event_id'], ['event_id'], source_schema='domain', referent_schema='core', ondelete='CASCADE')
    op.drop_constraint(None, 'fact_activity_template', schema='domain', type_='foreignkey')
    op.create_foreign_key(op.f('fact_activity_template_event_id_fkey'), 'fact_activity_template', 'event_facts', ['event_id'], ['event_id'], source_schema='domain', referent_schema='core', ondelete='CASCADE')
    op.drop_constraint(None, 'event_facts', schema='core', type_='foreignkey')
    op.create_foreign_key(op.f('event_facts_raw_id_fkey'), 'event_facts', 'event_raw', ['raw_id'], ['raw_id'], source_schema='core', referent_schema='raw', ondelete='SET NULL')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_table('event_memories', schema='core')
    # ### end Alembic commands ###
